"""Quantify each labeling evidence source's INDEPENDENT contribution,
per flood attack type, before redefining confidence-tier logic or building
attack-specific corroboration rules.

Context: the flood-pattern calibration run (scripts/calibrate_flood_pattern.py)
found only 2-3 victim-IP-corroborated instances per flood type, and their
entropy/port signature is contradictory across subtypes (ICMP/UDP flood look
uniform+concentrated, SYNflood/Goldeneye don't). Per explicit direction:
victim-IP corroboration is demoted from "primary calibration source" to an
auxiliary signal, and the shared `flood_pattern` category is being replaced
with per-attack-type rules. Before redesigning anything, this script
establishes the baseline evidence-overlap facts.

`TEIDFeatureRecord.label_evidence` (produced by `_classify()` in
preprocessing/labeling.py) already carries each of the three evidence levels
INDEPENDENTLY -- SCHEDULE/VICTIM_IP/PATTERN are appended to `evidence`
whenever level1/level2/level3 fire respectively, regardless of whether the
others fired (only `is_attack`/`label_confidence` are gated on level1/level2).
So this script does NOT need to recompute anything -- it cross-tabulates the
existing `label_evidence` field across ALL instances (not just is_attack=True
ones) to get true marginal and joint statistics for the three sources.

Reports, per flood type and combined:
  - Marginal positive rate of each evidence source (P(SCHEDULE), P(VICTIM_IP), P(PATTERN))
  - All 8 co-occurrence combinations (Venn regions)
  - Conditional rates: P(VICTIM_IP | SCHEDULE), P(PATTERN | SCHEDULE),
    P(VICTIM_IP | PATTERN), P(PATTERN | VICTIM_IP)

Usage:
    poetry run python scripts/quantify_evidence_sources.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))
sys.path.insert(0, str(PROJECT_ROOT))

from agente_5g.models.schedule_config import AttackSchedule, LabelPatternsConfig  # noqa: E402
from scripts.validate_labeling import process_file  # noqa: E402

REPORT_DIR = PROJECT_ROOT / "outputs" / "reports" / "evidence_quantification"

FLOOD_TYPES = ["ICMPflood", "UDPflood", "SYNflood", "Goldeneye"]
MAX_DURATION_S = 2200.0


def _pct(part: int, total: int) -> float:
    return round(100 * part / total, 1) if total else 0.0


def _venn_counts(records: list[Any]) -> dict[str, int]:
    counts = {k: 0 for k in ["000", "001", "010", "011", "100", "101", "110", "111"]}
    for r in records:
        s = 1 if "SCHEDULE" in r.label_evidence else 0
        v = 1 if "VICTIM_IP" in r.label_evidence else 0
        p = 1 if "PATTERN" in r.label_evidence else 0
        counts[f"{s}{v}{p}"] += 1
    return counts


def _conditional(n_num: int, n_den: int) -> str:
    return f"{_pct(n_num, n_den)}% (n={n_num}/{n_den})" if n_den else "n/a (n=0)"


def analyze(records: list[Any], label: str) -> dict[str, Any]:
    n = len(records)
    n_s = sum(1 for r in records if "SCHEDULE" in r.label_evidence)
    n_v = sum(1 for r in records if "VICTIM_IP" in r.label_evidence)
    n_p = sum(1 for r in records if "PATTERN" in r.label_evidence)
    n_sv = sum(
        1 for r in records if "SCHEDULE" in r.label_evidence and "VICTIM_IP" in r.label_evidence
    )
    n_sp = sum(
        1 for r in records if "SCHEDULE" in r.label_evidence and "PATTERN" in r.label_evidence
    )
    n_vp = sum(
        1 for r in records if "VICTIM_IP" in r.label_evidence and "PATTERN" in r.label_evidence
    )
    n_svp = sum(
        1
        for r in records
        if "SCHEDULE" in r.label_evidence
        and "VICTIM_IP" in r.label_evidence
        and "PATTERN" in r.label_evidence
    )
    venn = _venn_counts(records)
    return {
        "label": label,
        "n_total": n,
        "marginal": {
            "SCHEDULE": (n_s, _pct(n_s, n)),
            "VICTIM_IP": (n_v, _pct(n_v, n)),
            "PATTERN": (n_p, _pct(n_p, n)),
        },
        "venn": venn,
        "conditional": {
            "P(VICTIM_IP|SCHEDULE)": _conditional(n_sv, n_s),
            "P(PATTERN|SCHEDULE)": _conditional(n_sp, n_s),
            "P(VICTIM_IP|PATTERN)": _conditional(n_vp, n_p),
            "P(PATTERN|VICTIM_IP)": _conditional(n_vp, n_v),
            "P(SCHEDULE|VICTIM_IP)": _conditional(n_sv, n_v),
            "P(SCHEDULE|PATTERN)": _conditional(n_sp, n_p),
        },
        "all_three": _conditional(n_svp, n),
    }


def render(rows: list[dict[str, Any]]) -> str:
    lines: list[str] = []
    lines.append("# Evidence Source Independent Contribution (flood types, BS1)\n")
    lines.append(
        "Generated by `scripts/quantify_evidence_sources.py`. Cross-tabulates the three "
        "labeling evidence sources (SCHEDULE=Level1, VICTIM_IP=Level2, PATTERN=Level3) "
        "independently of each other and of `is_attack`/confidence gating, across ALL "
        "TEID-feature instances in each file (not just attack-labeled ones), as a factual "
        "baseline before redesigning per-attack-type flood corroboration rules or the "
        "confidence-tier formula.\n"
    )

    for row in rows:
        t = row["label"]
        lines.append(f"\n## {t}\n")
        lines.append(f"Total TEID-feature instances: {row['n_total']}\n")

        lines.append("### Marginal positive rate (independent of the other two sources)\n")
        lines.append("| Source | n | % of all instances |")
        lines.append("|---|---|---|")
        for name, (cnt, pct) in row["marginal"].items():
            lines.append(f"| {name} | {cnt} | {pct}% |")

        lines.append(
            "\n### Venn regions (S=SCHEDULE, V=VICTIM_IP, P=PATTERN; bits in that order)\n"
        )
        lines.append("| SVP | meaning | n | % |")
        lines.append("|---|---|---|---|")
        meanings = {
            "000": "none",
            "100": "schedule only",
            "010": "victim-IP only",
            "001": "pattern only",
            "110": "schedule+victim (current MEDIUM)",
            "101": "schedule+pattern, no victim (gated to LOW today)",
            "011": "victim+pattern, no schedule (outside window)",
            "111": "all three (current HIGH)",
        }
        for key in ["111", "110", "101", "011", "100", "010", "001", "000"]:
            cnt = row["venn"][key]
            lines.append(f"| {key} | {meanings[key]} | {cnt} | {_pct(cnt, row['n_total'])}% |")

        lines.append("\n### Conditional rates\n")
        lines.append("| Conditional | Value |")
        lines.append("|---|---|")
        for k, v in row["conditional"].items():
            lines.append(f"| {k} | {v} |")
        lines.append(f"| P(all three \\| any instance) | {row['all_three']} |")

    return "\n".join(lines)


def main() -> None:
    schedule = AttackSchedule.load(PROJECT_ROOT / "configs" / "attack_schedule.yaml")
    patterns = LabelPatternsConfig.load(PROJECT_ROOT / "configs" / "label_patterns.yaml")
    REPORT_DIR.mkdir(parents=True, exist_ok=True)

    rows: list[dict[str, Any]] = []
    combined_features: list[Any] = []
    for attack_type in FLOOD_TYPES:
        path = PROJECT_ROOT / "data" / "raw" / "BS1" / f"{attack_type}_BS1.pcapng"
        data = process_file(
            path,
            base_station="BS1",
            attack_type=attack_type,
            schedule=schedule,
            patterns=patterns,
            max_duration_s=MAX_DURATION_S,
        )
        features = data["features"]
        combined_features.extend(features)
        row = analyze(features, attack_type)
        rows.append(row)
        print(f"[{attack_type}] n={row['n_total']} marginal={row['marginal']}")

    rows.append(analyze(combined_features, "Combined (4 flood types)"))

    report_path = REPORT_DIR / "report.md"
    report_path.write_text(render(rows), encoding="utf-8")
    print(f"\nReport written to {report_path}")


if __name__ == "__main__":
    main()
